name: absensi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.0-134.5.beta <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  carousel_slider: 4.0.0
  google_fonts: 2.3.1
  http: 0.13.4
  get_storage: 2.0.3
  google_maps_flutter: 2.1.2
  geolocator: 8.2.0
  table_calendar: 3.0.4
  syncfusion_flutter_calendar: 19.4.56
  intl: 0.17.0
  image_picker: 0.8.4+11
  geocoding: 2.0.4
  datetime_picker_formfield: 2.0.0
  onesignal_flutter: 3.3.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/slider/
    - assets/images/
  uses-material-design: true
